data:
  batch_size: 64
  data_path: E:/code/data/simulated.csv
  drop_last: false
  feature_indices: null
  horizon: 3
  normalize: standard
  num_workers: 0
  sequence_length: 64
  shuffle_train: true
  target_indices: null
  train_split: 0.7
  val_split: 0.15
device: null
model:
  attention:
    add_positional_encoding: false
    dropout: 0.1
    enabled: true
    num_heads: 4
    variant: multiscale
    positional_mode: rope
  cnn:
    dropout: 0.1
    layers:
    - activation: relu
      kernel_size: 5
      out_channels: 32
      pool: max
      pool_kernel_size: 2
    - activation: gelu
      kernel_size: 3
      out_channels: 64
      pool: max
      pool_kernel_size: 2
    use_batchnorm: true
    variant: dilated
    use_channel_attention: true
    channel_attention_type: eca
  fc_hidden: 128
  forecast_horizon: 3
  lstm:
    bidirectional: true
    dropout: 0.1
    hidden_size: 128
    num_layers: 2
    rnn_type: lstm
train:
  checkpoints:
    dir: checkpoints
    save_best_only: true
  early_stopping:
    enabled: true
    min_delta: 0.0
    patience: 5
  epochs: 8
  gradient_clip: 1.0
  log_dir: runs
  loss: mse
  mixed_precision: false
  optimizer:
    lr: 0.001
    name: adam
    weight_decay: 0.0001
  print_every: 50
  scheduler:
    T_max: 20
    name: cosine
  seed: 42
