device: cuda  # 若无GPU可改为 null 或 cpu
output_dir: outputs/exp_3080ti_speed  # 统一输出目录，会自动前缀图片/日志/权重目录
visual_save_dir: image
visual_enabled: true

model:
  fc_hidden: 128
  forecast_horizon: 3
  cnn:
    variant: depthwise  # standard|depthwise|dilated
    dropout: 0.05
    use_batchnorm: true
    layers:
      - {out_channels: 32, kernel_size: 5, activation: relu, pool: max, pool_kernel_size: 2}
      - {out_channels: 64, kernel_size: 3, activation: gelu, pool: max, pool_kernel_size: 2}
  lstm:
    rnn_type: lstm     # lstm|gru
    hidden_size: 128
    num_layers: 2
    bidirectional: true
    dropout: 0.1
  attention:
    enabled: true
    variant: standard  # standard|multiscale
    num_heads: 4
    dropout: 0.1
    add_positional_encoding: false

data:
  data_path: data/simulated.csv   # TODO: 改为你的实际数据路径（CSV/NPZ/NPY）
  sequence_length: 64
  horizon: 3
  feature_indices: null
  target_indices: null
  train_split: 0.7
  val_split: 0.15
  normalize: standard
  batch_size: 512      # 显存充足，可继续上探到 640/768/896/1024
  num_workers: 12
  shuffle_train: true
  drop_last: true

train:
  epochs: 50
  loss: mse           # mse|mae|huber
  optimizer:
    name: adamw
    lr: 0.0015
    weight_decay: 0.0001
  scheduler:
    name: cosine
    T_max: 50
  early_stopping:
    enabled: true
    patience: 6
    min_delta: 0.0
  checkpoints:
    dir: checkpoints/3080ti_speed
    save_best_only: true
  gradient_clip: 1.0
  mixed_precision: true
  log_dir: runs/3080ti_speed
  seed: 42
  print_every: 50
  deterministic: false
  cudnn_benchmark: true
  matmul_precision: high

